### ISSUE TITLE
SMIP-0004: PoST util 2.0

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/SMIPS#14]
## Goals and Motivation

Change our [current](https://github.com/spacemeshos/post) PoST implementation so that:

* Proofs generation and validation will be done according to the new tree-free construction
* The Initialization phase PoW will be done using `scrypt` hashes on GPU instead of `sha256`’s on CPU, using the [gpu-post](https://github.com/spacemeshos/gpu-post) lib.

Since the combination of the 2 points above makes most of the current implementation code obsolete (including the dependency on [merkle-tree](https://github.com/spacemeshos/merkle-tree), written in Go), the new PoST util should be rewritten from scratch to better suit the new requirements. 

---

# New tree-free proof construction

### Definitions

* #### work-oracle
storage-filling hashes (`scrypt` with `sha512` or `blake3` as the last step)

* #### fast-oracle 
proof generation hashes (`sha256` or `blake3`)

### Parameters

* #### L (global, re-adjustable via the consensus protocol) = 64 
The amount of storage in bytes that work-oracle output fills. 64 is the max.
The lower L is, the greater the init cost.

* #### F (global, fixed) = 32
The fast-oracle output size in bytes.

* #### K1 (global, fixed) = 2000
Proof generation difficulty parameter.
The lower K1 is, the greater the difficulty. 

* #### K2 (global, fixed) = 1800
The number of label indices per proof.
The lower K2 is, the lower the difficulty. 

* #### S (chosen by each individual miner)
the amount of labels that the prover stores. 
For 256GiB space and L=64, S=4294967296

* #### K1/S: Proof difficulty threshold
For 256GB space and L=64, K1/S=2000/4294967296

* #### idxsz(S): Label index size
The size in bytes per label index in a proof, calculated as **ceil(log2(S)/8)**
For 256GiB space and L=64, idxsz(S)=4

#### Init
Given the prover id and S, generate and store j=0,1,2,3,…,S-1 labels such that each label is label_j=work-oracle(id,j)

#### Proving
Respond to challenge ch by using nonce=0 and creating proof(ch,nonce) as follows: loop over the stored j=0,1,2,3,…,S-1 labels, and whenever fast-oracle(ch,nonce,label_j) is smaller than K1/S difficulty threshold, concatenate the index j to the proof (more specifically, concatenate the idxsz(S) bytes that represent the index j to the proof). If K2 indices were already concatenated, increment nonce to nonce+1 and start again while discarding the previous work. The final proof is ch (32 or 20 bytes), nonce (4 bytes) together with the concatenated indices (idxsz(S) bytes each).

### Verifying

For each index j that was concatenated into proof(ch,nonce), verify that fast-oracle(ch,nonce,work-oracle(id,j)) is smaller than K1/S difficulty threshold. Number of indices should match K2, and must be unique. id and S are also part of the proof but provided separately.

--- 

## `gpu-post`

The `gpu-post` lib exposes a C-compatible API for generating batches of `scrypt` hash output data, according to a pre-defined input format. To be usable in the context of PoST, it must be managed by a higher application layer which will also be responsible for writing the data to disk, among other utilities. 

This layer should be directly linked with `gpu-post` as a shared library, because introducing IPC in such a low layer doesn’t make sense. 
To allow zero-overhead integration (including the in-process memory interface between the two sides), we should use C/C++/Rust. Rust is preferable due to its safety and since it's already being used in the [SVM](https://github.com/spacemeshos/svm) project. 

## The Greater PoST util

The complete PoST util will contain the following modules:

* `init`: integrating `gpu-post` to generate the init data and store it on the local filesystem
* `proving`: generate proofs through access to the init data file(s)
* `validating`: validate proofs generated by the `proving` module or by any other protocol-compatible lib
* `c-api`: expose all required high-level functionalities as C-compatible shared library
* `rpc`: expose all required high-level functionalities behind RPC server (gRPC/HTTP)

## Integration with `go-spacemesh`

Integration can be done either by linking with the shared library (`c-api` lib build artifacts), or the RPC server (running the `rpc` bin executable). 

For `init` and `proving` modules, using the RPC server will enable the utilization of a remote machine resources (processors, storage), but its setup is more complicated: one must build the PoST util separately, spawn it and connect to it over the network. This makes the RPC server usage undesirable in testing. 

For `validation`, such advantage doesn’t exist, as it is not intended to be used by the prover. Thus we expect this module to be always consumed as shared library.

## Integration as a shared library

The PoST util `c-api` artifacts can be integrated with `go-spacemesh` only via a custom `cgo` wrapper (similar to [go-svm](https://github.com/spacemeshos/go-svm), but much simpler).

# Additional features

* ### Incremental difficulty adjustment

Use the existing init data when applying a smaller L parameter. For example, if a user has 2^34 labels initialized with L=64 bytes (meaning a total of 2^40 bytes, i.e., 1 TiB), that user should now delete the least-significant 32 bytes from every label (freeing 512 GiB), and then initialize 2^34 new labels with L=32 to fill up the newly-freed space.

* ### Variable commitment size

Support additional API functions for adding/removing commitment space.

* ### List all available processors

Listing all available GPU processors is implemented internally by `gpu-post` lib. In addition, this should offer a CPU fallback.

* ### Benchmark all available GPUs

Run a short benchmark test to figure out what’s the most performant GPU available.

* ### Configure a specific GPU usage

Use a specific GPU for the init. This can be the result of a benchmark, or as arbitrary manual selection by the user. 

* ### Configure GPU throttle mode 

Use less GPU cores than what was defined as the optimal concurrency.

* ### CPU fallback

Implement a CPU-based fallback implementation for init in case no GPU is available on the system or if the user doesn’t wish to use it.  Open questions: 
1) Should it support CPU parallelism?
2) Should the CPU-scrypt hashes be used for proofs validation as well? Or should we attempt to  use the GPU-scrypt?

* ### Configure splitting the init data into multiple files

This is required so that users won’t need to deal with a single file which size a few hundreds GiB (or more). 

* ### Init crash recovery

The init state should be discovered solely from the filesystem view, without any additional info, and should allow the continuation of the procedure after a hard (unexpected) or a soft (upon request) shutdown. We can use this mechanism to implement the pause/resume mechanism as well, but this will require to kill the init process if one wishes to pause it. If we wish to avoid that, we’ll need to listen for incoming async pause requests while looping through the init work.  

* ### PoST util to support multiple miner ids per datadir

All the init data file(s) are to be stored within the configured `datadir` path, and the current PoST util implementation supports additional nesting per id, so that multiple ids can coexist. As discussed with @avive this feature will be removed. 

* ### Advertise progress

Asynchronously report the progress of the init work.

**Comment by avive** [comment]
We need to go over the proposed Smesher API and its commitment related methods and make sure we are aligned. It is supposed to support all the scenarios/ flow you list here. Part of the upcoming api review. Here: https://github.com/spacemeshos/api/blob/smeshing-methods/proto/spacemesh/smesher.proto

**Comment by moshababo** [comment]
Looks like the API for adding/removing commitment space is still missing.

Also, IMO there's no need for `CommitmentProgressStream`; `CreateCommitment` can return the stream of updates instead.

**Comment by avive** [comment]
Good feedback! here's the design rational: 

- Clients can modify (increase or decrease in size) via the same `CreateCommitment` method by just specifying different params (see comment in the api sketch). So there's no need for a specific method to modify.
- The reason for having a separate CommitmentProgressStream: we need to consider the case where a commitment generation is in progress and the node shuts down and starts up again. In this case, clients may provide the node the specified commitment via cli flags and not via an api call and they would like to receive commitment generation progress. Generally speaking, api methods can be provided via CLI params for max flexibility, and in the case of params provided as CLI flags clients can't obtain a stream such as the case when they call CreateCommitment api method. I hope this is clear enough...

**Comment by moshababo** [comment]
> Clients can modify (increase or decrease in size) via the same CreateCommitment method by just specifying different params (see comment in the api sketch). So there's no need for a specific method to modify.

:thumbsup:

> The reason for having a separate CommitmentProgressStream: we need to consider the case where a commitment generation is in progress and the node shuts down and starts up again. In this case, clients may provide the node the specified commitment via cli flags and not via an api call and they would like to receive commitment generation progress. Generally speaking, api methods can be provided via CLI params for max flexibility, and in the case of params provided as CLI flags clients can't obtain a stream such as the case when they call CreateCommitment api method. I hope this is clear enough...

The support for async progress request due to client crash/shutdown make sense. 

But there's no problem to support it via CLI: the wrapper will block until the RPC returns, meanwhile writing to console the stream of updates.

**Comment by avive** [comment]
> But there's no problem to support it via CLI: the wrapper will block until the RPC returns, meanwhile writing to console the stream of updates.

I should have been more accurate about the intent - all the non-streaming set/update/delete API methods should be supported via CLI flags for max flexibility and full node configuration w/o having to use an API client, but not the streaming methods which are designed to return a stream of protobufs messages over a connection to clients.

**Comment by avive** [comment]
About this: 
> PoST util to support multiple miner ids per datadir

I just think this is a really edge / fringe use case that we shouldn't really support right now.

About gpu-post: what's missing form the spec is the modification that @iddo333 wants to do to scrypt jane that we use in gpu compute considering the optimization for gpu constraints. e.g. our implementation is optimized for specific scrypt params but there is flexibility in others.

**Comment by avive** [comment]
Review on this before it is implemented will be great as well: https://github.com/spacemeshos/gpu-post/issues/3

**Comment by moshababo** [comment]
> I should have been more accurate about the intent - all the non-streaming set/update/delete API methods should be supported via CLI flags for max flexibility and full node configuration w/o having to use an API client, but not the streaming methods which are designed to return a stream of protobufs messages over a connection to clients.

CLI tools are usually built as wrappers around an API client. In this case, targeting stream and non-stream calls is the same - the tool blocks until it returns, and then write the response to console. If it's a stream call then it also write the stream of updates.

We can support CLI commands as part of the PoST util itself, but i'm not sure it will make sense - mainly because the end-user doesn't suppose to use it directly, but also because it will spawn a new process, which can conflicts with another running instance. 

> About gpu-post: what's missing form the spec is the modification that @iddo333 wants to do to scrypt jane that we use in gpu compute considering the optimization for gpu constraints. e.g. our implementation is optimized for specific scrypt params but there is flexibility in others.

I'll discuss with @iddo333.

**Comment by avive** [comment]
The goal of the CLI option is users who want to run a full node w/o interacting with it via the api - these users would like to specify everything as params when starting the node and not have to use an api client. I think we all agree we want to support this use case. So, at least a subset of the post related methods such as setting up a commitment and coinbase account should have CLI support. Otherwise, the only way to set post will be to start a node and use some API client to interact with it....

**Comment by lrettig** [comment]
@moshababo a few questions:

> L (global, re-adjustable via the consensus protocol) = 64
> The amount of storage in bytes that work-oracle output fills. 64 is the max.
> The lower L is, the greater the init cost.

Why 64? Does this give us enough scope to adjust difficulty in the future? I'm not sure I understand this math but based on your example:

> Use the existing init data when applying a smaller L parameter. For example, if a user has 2^34 labels initialized with L=64 bytes (meaning a total of 2^40 bytes, i.e., 1 TiB), that user should now delete the least-significant 32 bytes from every label (freeing 512 GiB), and then initialize 2^34 new labels with L=32 to fill up the newly-freed space.

it sounds like L=32 is 2x as hard as L=64? As a concrete example, Bitcoin difficulty today is 15.14e12. A few years ago it was on the order of 1e6-1e9. That's a factor of 1,000,000x.

> If K2 indices were already concatenated, increment nonce to nonce+1 and start again while discarding the previous work

What's the rationale behind this?

> Verifying
> For each index j that was concatenated into proof(ch,nonce), verify that fast-oracle(ch,nonce,work-oracle(id,j)) is smaller than K1/S difficulty threshold. id and S are also part of the proof but provided separately.

There needs to be some check that the right number of indices was provided, or that the provided indices are unique, right?

**Comment by lrettig** [comment]
> We can support CLI commands as part of the PoST util itself, but i'm not sure it will make sense - mainly because the end-user doesn't suppose to use it directly, but also because it will spawn a new process, which can conflicts with another running instance.

What will spawn a new process? And how would it conflict?

**Comment by lrettig** [comment]
> > PoST util to support multiple miner ids per datadir
> 
> I just think this is a really edge / fringe use case that we shouldn't really support right now. I can't even conceptualize how / when / who this feature will be useful for. If someone on the team wants to argue for it then please present the use case for it and argue that it is not a very minor one.

This would be, like, if a miner wanted to switch their miner ID after running init? Or to run init for a bunch of miner IDs so that they could switch their miner ID later? Or maybe if someone running multiple miners wants them all to share one gigantic datadir?

**Comment by avive** [comment]
I think that by design a commitment must be tied to 1 smesher id so it can't be reused by other smeshers and if you want to change your smesher id we want you to create a whole new commitment for this new id so you can't reuse older ones. As I said above, I never fully understood this use case because nobody was able to explain why/when/how it is useful.

**Comment by lrettig** [comment]
I am curious to hear such an explanation too :)

**Comment by moshababo** [comment]
> The goal of the CLI option is users who want to run a full node w/o interacting with it via the api - these users would like to specify everything as params when starting the node and not have to use an api client. I think we all agree we want to support this use case. 

You’re describing here the node's CLI tool, no?

> So, at least a subset of the post related methods such as setting up a commitment and coinbase account should have CLI support. Otherwise, the only way to set post will be to start a node and use some API client to interact with it....

> What will spawn a new process? And how would it conflict?

The PoST util is a lib, so it’s not intended to be used directly by the end-user. Even if it runs in RPC mode, it should be used only via the node in the normal use-case (the node has its CLI tool, so no one is required to set up an API client to use it).

If for some reason we do want end-users to use the PoST util directly, we should still do it by running it in RPC mode, and having a CLI tool (not the node’s one, but a different one) using an API client internally. If we want to have a CLI tool which doesn’t connect to a running PoST util instance RPC server, but rather spawn it as a new process (hence this is not a CLI tool, but rather just CLI params), we cannot use it for the stream calls (as you mentioned already), and also can’t guarantee not having conflicts in their operations: both of them might be writing to the same dir, etc. This approach isn’t recommended whenever an app (the PoST util) is having an internal state (IDLE, INITIALIZING, etc.). 

I think we have some misunderstandings here, so if what I wrote doesn’t change that, let’s talk privately. 

---

> Why 64? Does this give us enough scope to adjust difficulty in the future? I'm not sure I understand this math but based on your example:

> it sounds like L=32 is 2x as hard as L=64? As a concrete example, Bitcoin difficulty today is 15.14e12. A few years ago it was on the order of 1e6-1e9. That's a factor of 15,000,000x.

L=64 the output size of the work oracle.  L=32 is indeed 2x difficulty. We can go down until 1 bit. It’s limited compared to Bitcoin PoW difficulty, because it's using the numeric value of the hash output, while here we use its space (num of bits). So for example, it's similar to the difference between uint64 num of bits (=64), and uint64 max value (=18446744073709551615). 

> What's the rationale behind this?

I’m still not sure about this - it requires further discussions (see the research forum)

> There needs to be some check that the right number of indices was provided, or that the provided indices are unique, right?

Yes, I just didn’t specify it in the simple description, but I should add it.

**Comment by avive** [comment]
I think we can de-prioritize the auto throttling down when user is interactive on the system. I've been testing gpu-post on windows desktop systems with both amd and nvidia popular cards and user can browse the web and rung non-gpu-intensive apps while the compute is utilizing 99% of the gpu.

**Comment by countvonzero** [comment]
implemented, and also changed a lot since.
