### ISSUE TITLE
SMIP: Rewards Distribution Algorithm (Incentives Scheme) (WIP)

### ISSUE THREAD

**Issue by avive** [spacemeshos/SMIPS#19]
# Motivation

For Spacemesh 0.2 we want to implement a new rewards distribution algorithm that will determine the tx fee and block-reward distribution for different actions such as submitting a block that got into the mesh and participating in a hare committee. This algorithm will be executed by the STF as it modifies global state and creates global state side-effects such as rewards. 

## SMIPs considerations
We'll need to update the data SMIP, STF definition with this new spec. 

## API Considerations
Should be minimal. We'll need to add the action that is the cause of a reward to the Reward data item type. For example - block, hare, etc... as well as some context if possible, such as the layer number that the block or the hare rewards are for.

## Implementation Considerations
- We need to implement this as part of the STF and API implementation task.
- We might implement the naive rewards computation as specified now in the STF definition and the API around it as a short-term to be able to test other aspects of the stf and the api.

@tal-m @lrettig

**Comment by lrettig** [comment]
Closing in favor of #38
