### ISSUE TITLE
SMIP-0008: Compact block encoding scheme and Verifying Tortoise

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/SMIPS#2]
### *NOTE: This is a draft*
# Goals and Motivation

## Block encoding scheme

Our current implementation of blocks and mesh decoding (tortoise) is cheap on the encoder side, just record the view all seen orphan blocks and hare votes (`hdist` layers back), but this makes decoding expensive (`Ω(n^3)`) to decode a mesh with `n` blocks.

We suggest moving to a new, more efficient encoding scheme, in which decoding is only O(n^2) , and (in the optimistic case) block sizes are also smaller.

Generally speaking - instead of including view and votes, we will include a pointer to a block that we agree with its opinions and attach an exception list for differences. we also include the blocks that came after the base block that we have a neutral vote on. (since not including a block implicitly means voting against)

## Verifying Tortoise

NOTE: this is based on the new encoding scheme mentioned above

The “Verifying Tortoise” is an optimized algorithm that, given a proposed vote vector, can verify whether this would be the output of the full Tortoise algorithm much more efficiently than actually running the full Tortoise.

The new O(n) algorithm will work **as long as all assumptions were satisfied since genesis**. Which is a condition we require for the current tortoise as well.

TODO: more specifications about how this tortoise will work.

# Dependencies and Interactions

## Pending research -

*   DoS-prevention - still in progress
    * Basic version - limit size of exception list
*   resume after assumption corruption ( **self-healing** )

## Interaction with existing code- 

*   Big change in MeshDB and everything related to blocks and block structure(database structure)
*   Replaces the whole tortoise algorithm
* Probably has some impact on sync

# Implementation details

## Block Structure - 

A block B will include

*   A pointer to a single previous block X (base block)
*   A list of vote differences a.k.a exception list. for blocks in layers before X for which B’s opinion differs from X’s opinion
*   A list of explicit votes for blocks in the same layer as X or after.
This means eventually three list, one for each vector correction. 

```
Old structure:
Block {
   Hare_Votes: [<block_id>, <block_id>, <block_id>...]
   View_Edges: [<block_id>, <block_id>, <block_id>...]
}

New structure:
Block {
   Base_Block: <block_id>
   For_Exception_List: [<block_id>, <block_id>, <block_id>...] // List of blocks I vote For and Base_Block doesn't
   Against_Exception_List: [<block_id>, <block_id>, <block_id>...] // List of blocks I vote Against and Base_Block doesn't
   Neutral_Exception_List: [<block_id>, <block_id>, <block_id>...] // List of blocks I vote neutral and Base_Block doesn't or blocks that just come after Base_Block.
}
```

To be able to produce blocks we can define these basic modules:

*   Choosing the base block
*   Computing the allowable exception list length
*   Choosing which exceptions to include in the list.

## Tortoise algorithm: 

1. Mark the genesis block as “good”
2. Go over all blocks, in order.
    *   For block i , mark it “good” if (1) its base block is marked good and (2) its exception list consists only of blocks that appear after the base block and are consistent with the input vote vector.
3. Count the votes for the input vote vector by summing the weight of the good blocks (of course, each good block’s weight only counts for the blocks preceding it).
4. Declare the vote vector “verified” up to position k if the total weight exceeds the confidence threshold in all positions up to k .

In memory representation:

1. We keep a table that records, for each block, its votes about every previous block
2. We keep a vector containing our _vote totals_ (positive and negative) for every previous block
3. When a new block arrives, we look up the block it points to in our table, and add the corresponding vector (multiplied by the block weight) to our own vote-totals vector. We then add the vote difference vector and the explicit vote vector to our vote-totals vector.

### side notes
should be using a sliding window approach to keep memory usage reasonable. everything that has passed the `irreversible`  threshold should be kept on disk only.

### Open questions -

* What happens if hare votes are different in previous blocks. (probably because of adversary block)
  this is possible because we don't check hare votes. I guess nothing.
* Exception list should include only orphans that are not in previous layer ?

**Comment by antonlerner** [comment]
who creates the input vector to the verifying tortoise?

**Comment by y0sher** [comment]
I assumed the `input vote vector` is kinda like pbase and it is counted from genesis and gets stronger as more blocks vote the same way. see- 
`Count the votes for the input vote vector by summing the weight of the good blocks (of course, each good block’s weight only counts for the blocks preceding it).`
though I agree it isn't straight forward understood maybe we could get more clarification today..

**Comment by y0sher** [comment]
> Should the change to not have empty blocks anymore on the mesh but only blocks with transactions be part of this task or not?

this isn't a task, this is a design document that will result in multiple tasks eventually. so the answer is *no*.
