### ISSUE TITLE
SMIP-0010: Vaults

### ISSUE THREAD

**Issue by avive** [spacemeshos/SMIPS#22]
# Motivation

SmeshCash is a flexible, smart contract-based multisig wallet implemented in SVM and available to all users on the Spacemesh platform.

SmeshCash is a technology preview of Spacemesh programability features for Spacemesh 0.3.5. It is the only smart contract that is spawnable and functional on the first version of the mainnet. Spacemesh wallets are going to support SmeshCesh.

Beyond being a tech previoew. SmeshCash is designed to support enhanced funds security and functionality with features such as multi-sig master key, hardware wallets support, spending keys and vesting.

> Note: this spec moved from product repo.

# Use Cases

1. Create an on-mesh spending wallet with a single master key or multiple master keys (any of these keys can be hardware-wallet keys).
1. Daily spending limits enforced by the wallet: single daily amount. Applicable to all valid spending keys.
1. Generation of any number of replaceable "spending keys." These spending keys can be burned at any time, or replaced if lost, by the master key. For the first version, only up to 10 spending keys will be supported.
1. View vested and unvested coin balance.
1. Transfer up to the vested wallet balance from the wallet to another account or wallet.
1. Provide investors and builders with a way to track vesting and get their coins.

# Requirements

1. Support for spending key recycling, multi-sig master key, and daily spending limit.
1. Support funds vesting. Enforces spending rules over time based on wallet instance params.
1. Don't duplicate code for each wallet instance - use code templates.
1. Users interact with wallet using smart contract transactions and gasless "quasi transactions" (that don't change state).
1. Save wallet instance state in SVM storage trie.
1. Reference Spacemesh desktop wallet supports for SmeshCash. e.g. users should be able to interact with a wallet instance via the Spacemesh app UI.
1. Support pre-compiled instances with a pre-set balance, master key(s), and vesting params.
1. Receive funds from any other wallet or user coin account via a smart contract transaction.

## Wallet properties

- Total balance managed by the wallet.
- Balance funds available for withdrawals out of the total balance.
- Master key(s) - 1 key for single master, n keys for multi-sig. Need to support m-of-n multi-sig.
- Vesting enabled - true or false.
- Daily spending limit - changeable by owner master key(s).
- Spending public key(s) - changeable by owner of master key(s). Master key owner can retire old keys at any time and add new ones.

### Vesting Properties

This read-only properties are set for a vesting-enabled wallet. All of these properties must be set at wallet instantiation time and can't be changed later by anyone.

1. Vesting start time. e.g. a layer # from genesis.
2. Vesting start amount. e.g. 3000 coins. The amount that can be withdrawn at the vesting start time.
3. Vesting period length. The time period in which vesting withdrawals can be made starting with the first vesting period after the vesting start timestamp. e.g. one calendar month (specified in num of layers).
4. Vesting period amount. e.g. 500 coins. The amount that can be drawn by the end of each vesting period.

For example, key owner of a vesting wallet may withdraw the the `vesting start amount` on or after the `vesting start time`. On or after the time of the `vesting start time` plus the `vesting period` they may withdraw the vesting period amount.

### Wallet Instantiation

We need to support 2 main instances types:
1. Pre-compiled instances: Instances pre-compiled into the SVM storage trie at genesis.
2. User-instantiated instances: Instances created by users via a smart contract transactions.

For user-instantiated wallets, all properties must be set at creation time in the instantiation transaction.

**Comment by avive** [comment]
First implementation limitations:
1. Only up to 10 spending keys per wallet and not unlimited number of keys.
2. Only 2 out of 3 options for multi-sig master key.

**Comment by poy5861R** [comment]
> # แรงจูงใจ
> SmeshCash เป็นกระเป๋าสตางค์ multisig ที่ใช้สัญญาที่ยืดหยุ่นและใช้งานได้ใน SVM และผู้ใช้ทุกคนบนแพลตฟอร์ม Spacemesh
> 
> SmeshCash เป็นตัวอย่างเทคโนโลยีของคุณสมบัติการเขียนโปรแกรมของ Spacemesh สำหรับ Spacemesh 0.3.5 เป็นสัญญาอัจฉริยะเพียงสัญญาเดียวที่วางไข่และใช้งานได้บน mainnet รุ่นแรก กระเป๋าอวกาศ Spacemesh กำลังจะสนับสนุน SmeshCesh
> 
> นอกเหนือจากการเป็นเทคโนโลยีที่เหนือกว่า SmeshCash ได้รับการออกแบบมาเพื่อสนับสนุนความปลอดภัยและการทำงานของกองทุนที่เพิ่มขึ้นด้วยคุณสมบัติเช่นคีย์หลักแบบ multi-sig, การสนับสนุนกระเป๋าเงินฮาร์ดแวร์, คีย์การใช้จ่ายและการมอบสิทธิประโยชน์
> 
> > หมายเหตุ: ข้อมูลจำเพาะนี้ย้ายจาก repo ผลิตภัณฑ์
> 
> # ใช้เคส
> 1. สร้างกระเป๋าเงินใช้จ่ายในตาข่ายด้วยคีย์หลักเดียวหรือหลายคีย์หลัก (คีย์ใด ๆ เหล่านี้สามารถเป็นคีย์กระเป๋าเงินฮาร์ดแวร์)
> 2. ข้อ จำกัด การใช้จ่ายรายวันที่บังคับใช้โดยกระเป๋าเงิน: จำนวนเงินรายวันเดียว ใช้กับคีย์การใช้จ่ายที่ถูกต้องทั้งหมด
> 3. การสร้าง "คีย์การใช้จ่าย" ที่สามารถเปลี่ยนได้จำนวนเท่าใดก็ได้ คีย์การใช้จ่ายเหล่านี้สามารถเขียนได้ตลอดเวลาหรือเปลี่ยนใหม่หากสูญหายโดยมาสเตอร์คีย์ สำหรับรุ่นแรกสนับสนุนคีย์การใช้จ่ายสูงสุด 10 คีย์เท่านั้น
> 4. ดูความสมดุลของเหรียญที่ได้รับและไม่ได้ลงทุน
> 5. โอนเงินไปยังยอดเงินคงเหลือ Wallet จากกระเป๋าเงินไปยังบัญชีอื่นหรือกระเป๋าเงิน
> 6. ให้นักลงทุนและผู้สร้างด้วยวิธีการติดตามการได้รับเหรียญของพวกเขา
> 
> # ความต้องการ
> 1. สนับสนุนการใช้จ่ายการรีไซเคิลคีย์รหัสหลักแบบหลาย sig และ จำกัด การใช้จ่ายรายวัน
> 2. กองทุนสนับสนุนการมอบสิทธิ์ บังคับใช้กฎการใช้จ่ายตลอดเวลาตามพารามิเตอร์อินสแตนซ์กระเป๋า
> 3. อย่าทำซ้ำรหัสสำหรับกระเป๋าเงินแต่ละครั้ง - ใช้แม่แบบรหัส
> 4. ผู้ใช้โต้ตอบกับกระเป๋าเงินโดยใช้การทำธุรกรรมสมาร์ทและไม่มี "ธุรกรรมเสมือน" (ที่ไม่เปลี่ยนสถานะ)
> 5. Save wallet instance state in SVM storage trie.
> 6. Reference Spacemesh desktop wallet supports for SmeshCash. e.g. users should be able to interact with a wallet instance via the Spacemesh app UI.
> 7. Support pre-compiled instances with a pre-set balance, master key(s), and vesting params.
> 8. Receive funds from any other wallet or user coin account via a smart contract transaction.
> 
> ## Wallet properties
> * Total balance managed by the wallet.
> * Balance funds available for withdrawals out of the total balance.
> * Master key(s) - 1 key for single master, n keys for multi-sig. Need to support m-of-n multi-sig.
> * Vesting enabled - true or false.
> * Daily spending limit - changeable by owner master key(s).
> * Spending public key(s) - changeable by owner of master key(s). Master key owner can retire old keys at any time and add new ones.
> 
> ### Vesting Properties
> This read-only properties are set for a vesting-enabled wallet. All of these properties must be set at wallet instantiation time and can't be changed later by anyone.
> 
> 1. Vesting start time. e.g. a layer # from genesis.
> 2. Vesting start amount. e.g. 3000 coins. The amount that can be withdrawn at the vesting start time.
> 3. Vesting period length. The time period in which vesting withdrawals can be made starting with the first vesting period after the vesting start timestamp. e.g. one calendar month (specified in num of layers).
> 4. Vesting period amount. e.g. 500 coins. The amount that can be drawn by the end of each vesting period.
> 
> For example, key owner of a vesting wallet may withdraw the the `vesting start amount` on or after the `vesting start time`. On or after the time of the `vesting start time` plus the `vesting period` they may withdraw the vesting period amount.
> 
> ### Wallet Instantiation
> We need to support 2 main instances types:
> 
> 1. Pre-compiled instances: Instances pre-compiled into the SVM storage trie at genesis.
> 2. User-instantiated instances: Instances created by users via a smart contract transactions.
> 
> For user-instantiated wallets, all properties must be set at creation time in the instantiation transaction.

**Comment by avive** [comment]
@poy5861R Can you please post your comment in English?

**Comment by y0sher** [comment]
@avive I think this is a translation..

**Comment by YaronWittenstein** [comment]
1. When a simple coins transaction has an app account as the destination - Node should call `SVM` with a `before transfer hook` method.

2.  When the Wallet constructor (part of `spawn app`) is called with non-multi sig mode (i.e only a single master key), it should also pass the `spending key` and `spending daily limit` to constructor params. 

When working with multi-sig mode, we should use `set spending key` and `set spending daily limit` as part of a 2/3 flow. 

3. The Wallet could have only a single pending transaction per category.

4. The Wallet transaction categories will be: 
* Set a new spending key
* Set a new spending daily limit
* Withdraw coins

5. There should be a `cancellation flow` for each pending transaction.
It's relevant only when working with multi-sig mode.

The two parties that didn't create the pending transaction could together cancel the pending transaction.

6. Each pending transaction will have an expiration.

7. Each pending cancel-transaction will have an expiration

**Comment by countvonzero** [comment]
implemented as precompile now.
