### ISSUE TITLE
Sync definition

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/SMIPS#24]
## Overview
As part of the reivew for the new sync algorithm, it has made clear that while the new suggested method is better and more robust to actually fetch sync items from peers, it is important to have a clear definition of when a node is considered as "synced". Since the actial definition and data required to determine whether a node is synced or not may change the way we implement new sync and fetch mechanism

## current state
Currently, the sync algorithm is implemented in a pretty straight forward way. Main sync loop iterates from genesis layer to the last ticked layer
for each layer sync requested
- block ids for layer
- actual blocks

for each block synced a routine called 'data availability' is run, for each block the following data is synced:
-  missing blocks from view
- ATX
- TXs
- reference block if exist
- active set ids if exist

after syncing synced blocks are validated
- view is validated and missing blocks fetched and validated
- votes are validated - missing blocks are fetched and validated as well

### post sync 
When a node is syncing, no blocks can be created and gossiping of data forward is halted until syncing is done.
After all layers has been synced until the current one, syncer does not allow gossiping and block creation yet, and waits for 2 full layers while listening to gossip and not forwarding the messages.
This is to make sure that no messages were missed while not listening to gossip.

## new sync design
new sync will sync the mesh from genesis layerto current layer
- for each layer a layer has will be requested, a layer has will be the hash of all block ids received in this layer. After all block IDs received the layer hash can be compared and verified
q: how do we know this is the correct layer hash?
q: is it ok to have different layer hashes from different nodes? do we need to choose the layer hash that majority of peer nodes return for a layer id?
- for each block id - request it from a single peer, perform `dataAvailability` for each block and fetch missing atxs and txs
    - each tx and atx ID is the hash of its data - allowing to verify the integrity of the data
    - block verification will also be done as before

### different method for syncing
- listen to gossip network and start syncing from the current layer
    - this sync the node from latest till genesis following blpoc

### open questions
- is the iteration from genesis to current layer the best possible way to sync
- how do we guarantee that the synced data is the correct one for the network?
    - how do we validate the data
    - how do we avoid spoofing of blocks and sort of eclipse attacks

**Comment by antonlerner** [comment]
- send hash + list of ids received in last 30 (prop. delta) secs
- calc new mesh hash from blocks previous to the current layer we are syncing
- if we have a layer without blocks it will be the hash of the layer number

## Handle network splits:
- we need to aggregate layer hash (mesh hash)
- store both aggregated and non aggregated hash for a layer
- we need to do sync from time to time
- sync every 2 mins seconds and agree on mesh hash with my peers 
    - check that we agree on the last layer mesh hash
- drop peers that send data that don't match layer hash
- if during sync a new block is requested - get it and gossip it to others

**Comment by lrettig** [comment]
Another note from our conversation just now: as @iddo333 pointed out, there's a potential concurrency issue here, since this is an interactive protocol and a node may receive an old block that changes their view of the layers being synced after the sync process begins. It will therefore be critical to establish a "sync point" in time after which new data will not be considered - which may require a state snapshot, ideally using a clever data structure that allows a shallow copy/copy on write or something along those lines so the operation isn't too expensive.

**Comment by lrettig** [comment]
@iddo333 you wrote some Rust code that actually performs some of this operation already, when we were working on the rust client last year right? Is it worth sharing that here?

**Comment by antonlerner** [comment]
layer hash should only consist of contextually valid blocks, we need to be synced on all contextually valid blocks
I need to have all blocks in `k` last layers 
Contextually invalid blocks votes still count as valid blocks

**Comment by antonlerner** [comment]
The algorithm to sync blocks according to the new requirements are as following:

On the initiator side:
1. Get hash of current verified layer from peers
2. if hash is not equal to own hash
3. Binary search for first unequal aggregated hash

1. For each unequal hash
2. Send list of block ID's to peer
3. Receive list of missing blocks from peer
4. Get list of missing blocks from peer

On receiver:
1. listen to requests
2.for each unequal hash
3. receive list of blocks
4. if there are any blocks that are not present in db -request them from initiator

**Comment by countvonzero** [comment]
design is made obsolete by current implementation.
