### ISSUE TITLE
Tortoise Beacon

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/SMIPS#29]
## Motivation
Tortoise beacon is needed to calculate block creation eligibility - we currently have a mock beacon that is not secure at all.
To provide a valid beacon we must have some random value on which all nodes agree whithin a certain time frame. 

## Proposed solution
1. Proposal Phase: smeshers submit a “proposal” for randomness to be included in the beacon.
2. Consensus Phase: smeshers run a consensus protocol to agree on which proposals are valid (i.e., will be included in the beacon).
3. Output: the valid proposals are concatenated, and the hash of this string is the beacon value.

The proposed solution for creating a beacon is as follows:

1. Create a proposal for a beacon:
    - take all ATXs received in last epoch (i -1)
    - concat them into a single proposal message and sign it
    - Each smesher partitions the valid proposals received in the previous epoch into three sets:
        - Timely proposals: received up to δ after the end of the previous epoch.
        - Delayed proposals: received between δ and 2δ after the end of the previous epoch.
        - Late proposals: more than 2δ after the end of the previous epoch. Note that honest users cannot disagree on timing by more than δ, so if a proposal is timely for any honest user, it cannot be late for any honest user (and vice versa).
    - A party’s initial input to the consensus algorithm is the set of timely proposals.
2. Reach consensus over set of ATXs to construct a beacon from
    - for K rounds : in each round that lasts δ, wait for proposals to come in
    - create a voting message that references all seen proposals within δ time frame and send it
    - for next rounds wait for δ time, and construct a message that points to all messages from previous round received by δ
    - After K rounds had passed, tally up votes for proposals using simple tortoise vote counting
3. Create random beacon coin
    - for all messages that passed the global voting threshold, take the ATXs they have pointer on
    - hash all ATX into a single value
    - Beacon value received

## Implementation details
A new protocol must be created for this task, this protocol involves all participating nodes
Q: should it include all nodes or just nodes that have created an ATX? 
All nodes must gossip their proposals - (which can take quite a while)
After proposals are received a new message is constructed with only votes (and weak coin) 
Q: if all parties release proposals, and all parties vote on all proposals - won't it cause messages to be very very large?
Also, if we sample and only vote for some proposals - if each honest node will vote for different proposals none of them will pass global threshold.
Can sending only proposals that have passed a certain threshold solve this?
Q: we know that simple tortoise protocol work fine for only a certain window size - is this the case?

### network throughput optimisations
This protocol is very network intensive so some optimisation might be needed from the start:
1. de duplication of same proposals and votes for proposals by hash : vote for a hash of set of values for the chance that honest nodes will vote for same sets and therefore will not need to receive different messages
2. send proposals and votes in batches: have each proposal sent in numbered chunks - a message will be considered invalid if not all chunks have beed received by δ time.
3. sending only proposals that have passed a certain threshold.

### bootstrapping the protocol
This protocol is very network intensive and have multiple rounds until consensus is reached. this means that from the start of epoch 2 we will start constructing our beacon, however we will already need the beacon before so that blocks can be created at the start of same epoch
For that we must bootstrap the beacon from an external source
Current solution is to take the hash of the Bitcoin chain at block-height X as the beacon

### randomness external source
1. another centralised server?

**Comment by avive** [comment]
q: can't the agreement on a new random value be part of the Hare protocol to avoid running yet another consensus mechanism?

**Comment by antonlerner** [comment]
- ATXs in proposal can be reduced to only ATXs that pass a certain value
- We vote for ATXs in proposals
- encode ATXs in bit vector
- genesis will contain a public key and the beacon will be what is signed by that key

**Comment by countvonzero** [comment]
implemented.
