### ISSUE TITLE
Address Derivation from Public Key and Display

### ISSUE THREAD

**Issue by avive** [spacemeshos/SMIPS#41]
# Motivation
Well define how to generate an account address from a public key and the canonical string representation of an address to users.

# Specification
Input: a public key P.
- Hash P using SHA-256 to obtain a 32 bytes hash H.
- Take last 20 bytes H (H[12..32]) to create address A. For example, see Address.SetBytes() in go-sm code.
- Use an EIP55 compliant method to generate S - the canonical hex string representation of A. For example, see Address.Hex() in go-sm code.
- Always use S when displaying an address in a client to users and when outputting it to log files.

**Comment by countvonzero** [comment]
implemented
