### ISSUE TITLE
New SMIP Template

### ISSUE THREAD

**Issue by avive** [spacemeshos/SMIPS#5]
Mentioned here:
https://github.com/spacemeshos/SMIPS/blob/master/Epic%20Design%20Review%20Process

Where is the epic draft template in this repo?

**Comment by avive** [comment]
@noamnelke - please add the epic template to the master branch

**Comment by daonb** [comment]
@noamnelke I'm thinking of starting a new SMIP for "systemtest roadmap 2021". I was looking for a SMIP #1 - a guide as to how to add a SMIP but it's MIA. 

I guess a template will have to do for now. Where can I find it?

**Comment by avive** [comment]
https://github.com/spacemeshos/SMIPS/blob/master/.github/ISSUE_TEMPLATE/smip.md
